local_pubs: [/odom,/move_base/status,/move_base/result,/rs_front/QR_localization_complete,/rs_back/QR_localization_complete,/rs_left/QR_localization_complete,/rs_right/QR_localization_complete]
local_tf: []
